@mainUrl = http://localhost:3000
###
#
GET {{mainUrl}}/dburi1
###
#
GET {{mainUrl}}/dburi2
###
#
GET {{mainUrl}}/dburi3
###
#
GET {{mainUrl}}/copii
###
#
GET {{mainUrl}}/sesiuni



###
#
POST http://localhost:3000/sesiuni
Content-Type: application/json

{
    "date":"1975-08-30",
    "time":"16:00" 
}

###
#
POST http://localhost:3000/roboti
Content-Type: application/json

{
    "name":"Sphero"
}

###
#
POST http://localhost:3000/dburi1
Content-Type: application/json

{
    "info1":"Iron-Man Gauntlet",
    "RobotiId":2
}

###
#
POST http://localhost:3000/dburi2
Content-Type: application/json

{
    "info2":"RandomInfo"
}

###
#
POST http://localhost:3000/dburi3
Content-Type: application/json

{
    "info3":"RandomInfo"
}
###
#
DELETE http://localhost:3000/sesiuni
Content-Type: application/json

{
    "sesiuneId":8
}

###
#
DELETE http://localhost:3000/copii
Content-Type: application/json

{
    "copilId":1
}

###
#
DELETE http://localhost:3000/roboti
Content-Type: application/json

{
    "robotId":1
}

###
#
DELETE http://localhost:3000/dburi1
Content-Type: application/json

{
    "db1Id":1
}

###
#
DELETE http://localhost:3000/dburi2
Content-Type: application/json

{
    "db2Id":1
}

###
#
DELETE http://localhost:3000/dburi3
Content-Type: application/json

{
    "db3Id":1
}



###
#
PUT  http://localhost:3000/sesiuni
Content-Type: application/json

{
    "Id":3,
    "value.date":"1975-08-33",
    "value.time":"12:34"
    
}
###
#
POST http://localhost:3000/copii
Content-Type: application/json

{
    "name": "Ionut",
    "number":"939393939",
    "SesiuniId":2
}



