@mainUrl = http://localhost:3000
###
#
GET {{mainUrl}}/ruta
###
#
POST http://localhost:3000/sesiuni
Content-Type: application/json

{
    "date":"1975-08-19",
    "time":"12:00"
}
###
#
DELETE http://localhost:3000/sesiuni
Content-Type: application/json

{
    "sesiuneId":1
}




